### ISSUE TITLE
Python Code not working 2

### ISSUE THREAD

**Issue by tony1tf** [MaxusDev/MWTool#2]
This issue #1 has been closed, but the problem not fixed, so I am opening a new issue since I cannot re-open the one closed by the owner. By saying 'The communication protocol has been updated', are you saying that the latest devices have firmware which doesn't enable raw data by default? If so, then you must update your Python code to enable raw data when the trigger button is pressed. In any case, I have experimented with 'AT+DEBUG=0002' from the terminal, and never seen any raw data from the device. You have also not answered my question about how new firmware can be uploaded.

@tony1tf
 
 
Leave a comment
Attach files to your comment
Attach files by dragging & dropping, selecting or pasting them.
Assignees
No one assigned
Labels
None yet
Projects
None yet
Milestone
No milestone
Notifications
Customize
You’re receiving notifications because you authored the thread.
2 participants
@tony1tf
@MaxusDev

**Comment by tsanchez04** [comment]
I cannot get GUI to work correctly.  I open the GUI, select the comport.  Then when I press trigger nothing happens.  I press pause, then the program become non responsive.

**Comment by tony1tf** [comment]
Hi  tsanchez04
Yes, I have the same problem. Apart from baud rate updates on the
description, MaxusDev has been rather unresponsive, and not much progress
from SEEED Studio either.
Tony

**Comment by vortexsystems** [comment]
I cannot get GUI to work correctly. I open the GUI, select the comport. Then when I press trigger nothing happens. I press pause, then the program become non responsive.

I was able to get the radar working with teraterm and labview using AT commands.   Hopefully Maxus releases a programming reference to know what and how to use AT command interface.

**Comment by MaxusDev** [comment]
> This issue #1 has been closed, but the problem not fixed, so I am opening a new issue since I cannot re-open the one closed by the owner. By saying 'The communication protocol has been updated', are you saying that the latest devices have firmware which doesn't enable raw data by default? If so, then you must update your Python code to enable raw data when the trigger button is pressed. In any case, I have experimented with 'AT+DEBUG=0002' from the terminal, and never seen any raw data from the device. You have also not answered my question about how new firmware can be uploaded.
> 
> @tony1tf
> 

Hi tony, did you manage to get the raw data now? All the devices we delivered are of latest version and capable of sending raw data with AT commands. We apology that the document is not timely updated and we will be more responsive in the future correspondence.

Python code is only tested on MacOS. For Windows version, we will use Pyinstaller to create windows executable. Both Python and Node code will be updated these days. We appreciate your patience.

Thank you.

**Comment by MaxusDev** [comment]
> I cannot get GUI to work correctly. I open the GUI, select the comport. Then when I press trigger nothing happens. I press pause, then the program become non responsive.
> 
> I was able to get the radar working with teraterm and labview using AT commands. Hopefully Maxus releases a programming reference to know what and how to use AT command interface.

Hi  tsanchez04

Can you get the raw data? The Python is only tested on MacOS. Both Python and Node code will be updated these days. From another issue you mentioned the AT command list, currently there are five commands available. Here we go:

- Radiated power ```AT+PA=x```
The radiated power has 7 levels (0000~0007) for developer to choose. With the bigger number the device radiated more power.
- Receive gain  ```AT+REVGAIN=x```
The receive gain has 7 levels (0000~0007) for developer to choose. With the bigger number the device becomes more sensitive.
- Time delay ```AT+DELAY=x```
The time delay represent how long VOUT stays high after the device detects object. Developers can choose number from 0001~3599 (unit in second).
- Working mode ```AT+DEBUG=x```
By default the device works at normal mode, x = 0000. Developer can use x = 0002 to fetch raw radar data.
- Detect threshold ```AT+THRES=x```
The threshold (0001~0099) represents how easy the device to trigger detection. With lower number the device is more inclined to trigger detection which could be a false alarm.

Radiated power, receive gain and detection threshold have a complicated relationship and should be set probably according to your situation to ensure proper functioning of the device.

**Comment by tony1tf** [comment]
Hi MaxusDev

Still no raw data, even though the Vout signal detects a reflection.
Is there a command to list the settings, other than power off and on, when
the unit goes back to default configuration?

Tony

**Comment by MaxusDev** [comment]
> Hi MaxusDev Still no raw data, even though the Vout signal detects a reflection. Is there a command to list the settings, other than power off and on, when the unit goes back to default configuration? Tony
> […](#)

Hi  Tony

You can use ```?``` in all the AT commands to read the corresponding configuration. Simply just try ```AT+DEBUG=?```. By the way, can you provide me more info regarding your system, type of USB2TTL module, serial port application etc.? Please join our [slack](https://join.slack.com/t/mw0582/shared_invite/enQtOTIyMjI3MzcyOTMwLWM0ZGI2Njk3NTEzMjkwYjNjOTk0NDcwN2Y2YTdhOGM2NmJmYzZmZTUzMDZmOTI0MWExOTUyNzNmZmNlM2U5MDY).

Thank you.

**Comment by MaxusDev** [comment]
> I cannot get GUI to work correctly. I open the GUI, select the comport. Then when I press trigger nothing happens. I press pause, then the program become non responsive.
> 
> I was able to get the radar working with teraterm and labview using AT commands. Hopefully Maxus releases a programming reference to know what and how to use AT command interface.

Hi tsanchez04,

Can you provide me the type of your serial adapter?

Thank you!

**Comment by vortexsystems** [comment]
I am just using a sparkfun FTDI usb to ttl adapter.  https://www.sparkfun.com/products/13263

**Comment by MaxusDev** [comment]
Hi Tony

Since you can get the raw data now. I will close this issue. 

Thank you again for your feedback!

**Comment by kriedel** [comment]
You have to set the device in debug mode with the described command, then you will get data over the serial interface and the python app works fine. I tested it under windows 10 and Ubuntu 18. I used a USB adapter from FTDI.
