### ISSUE TITLE
Baud rate change

### ISSUE THREAD

**Issue by Shulyaka** [MaxusDev/MWTool#6]
Is it possible to change the baud rate? I want to hook it up with xbee, but 512000 is not among the supported baud rates for xbee.

**Comment by 0x6d7a** [comment]
> Is it possible to change the baud rate? I want to hook it up with xbee, but 512000 is not among the supported baud rates for xbee.

@Shulyaka the baudrate could be changed. We need to rebuilt a hex for new baudrate. Sorry for the late reply.
