### ISSUE TITLE
AT+LIGHT=xxxx command / LED

### ISSUE THREAD

**Issue by czietz** [MaxusDev/MWTool#7]
My MW0582TR11 has an on-board LED. What is its function? How can it be controlled? I can see from the boot message that there is a `LIGHT` setting and a corresponding `AT+LIGHT=xxxx` command. But what does this command do? Is it related to the LED? What are the possible parameters?

**Comment by czietz** [comment]
I figured it out myself: It's not an LED but a photo-diode, measuring ambient light level. The `AT+LIGHT=xxxx` command allows to set a threshold so that the output is only triggered when it is dark enough. The module accepts values 0000 - 9999. I don't know the range of sensible values. The higher the value, the darker it must be for the module to trigger the output when a moving object is detected.

**Comment by ArtanH** [comment]
Thanks a lot, for this information.
